language: ruby
sudo: false
cache: bundler # cache bundled gems from build to build
rvm:
  - 2.3.3
script: bundle exec rake
deploy:
  provider: script
  script: ci/travis-deploy.sh
  on:
    tags: true
  skip_cleanup: true
